### PR TITLE
feat: add a remove function

### PR DESCRIPTION
**Pull request by OtGabaldon**
## Conventional Commit

```text
feat: add a remove function (ENGCE-31031)

add  remove function and interpreter to the package.
```

### CODE REVIEW

**Review by StephenHanzlik — DISMISSED** [review]

**Review by rockymadden — APPROVED** [review]

**Comment by rockymadden** [comment]
Oh, @OtGabaldot, you likely want to add a TS sig for export. One sec.

**Review by rockymadden — CHANGES_REQUESTED** [review]
Here is the file you'd need to add the signature to. This will allow you to use TypeScript with proper typing when you limport and leverage.

https://github.com/cloud-elements/jmespath.js/blob/master/src/jmespath.d.ts

**Comment by OtGabaldon** [comment]
> Here is the file you'd need to add the signature to. This will allow you to use TypeScript with proper typing when you limport and leverage.
> 
> https://github.com/cloud-elements/jmespath.js/blob/master/src/jmespath.d.ts

I added:
`export function remove(jsonDoc: any, query: string): any;`

**Comment by OtGabaldon** [comment]
Merged manually through cli with changelog

**Pull request closed without merging**
